name: Sync Leetcode
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # STEP 1: FORCE GIT IDENTITY REGISTRATION
      - name: Configure Git Author Profile
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"

      # STEP 2: SYNC LOGIC
      - name: Sync
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
          filter-duplicate-secs: 86400
