name: Sync Leetcode
on:
  workflow_dispatch: # Allows you to manually trigger it
  schedule:
    - cron: "0 8 * * 6" # Runs automatically every Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
          filter-duplicate-secs: 86400
